config/routes.rb
Rails.application.routes.draw do
  
  get "payments/express"

  resources :attachments
  resources :payments
  resources :posts

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks",
                                  registrations: "registrations"}

  resources :users

  post "users/follow"
  
  get 'welcome/index'

  get "/cart", to: "payments#cart"

  get "transactions/checkout"

  get "/purchases", to: "payments#purchases"

  root 'welcome#index'

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :post
  #include Picturable


	after_save :save_image

	#if self.respond_to?(:name)
	FILE_PATH = File.join Rails.root, "public", "files" #, "attachments"
	#else
	#	FILE_PATH = File.join Rails.root, "public", "files", "posts"
	#end
	

	def file=(file)
		unless file.blank?
			@file = file
			if self.respond_to?(:name)
				self.name = file.original_filename.split(".").first.downcase
			end
			self.extension = file.original_filename.split(".").last.downcase
		end
	end

	def image_path
		File.join FILE_PATH, "#{self.id}.#{self.extension}"
	end

	def had_file?
		File.exists? image_path
	end

	private
	def save_image
		if @file
			FileUtils.mkdir_p FILE_PATH
			File.open(image_path, "wb") do |f|
				f.write(@file.read)
			end
			@file = nil
		end
	end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]

  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment, notice: 'Attachment was successfully created.' }
        format.json { render :show, status: :created, location: @attachment }
      else
        format.html { render :new }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @attachment }
      else
        format.html { render :edit }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachments_url, notice: 'Attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:name, :extension, :post_id, :file)
    end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_form.html.erb
<%= form_for(@attachment) do |f| %>
  <% if @attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% @attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file %>
    <%= f.file_field :file%>
  </div>
  <div class="field">
    <%= f.label :post_id, "Post" %>
    <%= f.collection_select :post_id, Post.all, :id, :tittle %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<h1>lista de adjuntos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Extension</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
        <td><%= attachment.name %></td>
        <td><%= attachment.extension %></td>
        <td><%= attachment.post %></td>
        <td><%= link_to 'Show', attachment %></td>
        <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
        <td><%= link_to 'Destroy', attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @attachment.name %>
</p>

<p>
  <strong>Extension:</strong>
  <%= @attachment.extension %>
</p>

<p>
  <strong>Post:</strong>
  <%= @attachment.post %>
</p>

<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>