config/routes.rb
Rails.application.routes.draw do
  
  get "payments/express"

  resources :attachments
  resources :payments
  resources :posts

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks",
                                  registrations: "registrations"}

  resources :users

  post "users/follow"
  
  get 'welcome/index'

  get "/cart", to: "payments#cart"

  get "transactions/checkout"

  get "/purchases", to: "payments#purchases"

  root 'welcome#index'

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :post_id, presence: true
  validates :user_id, presence: true

  before_save :default_values

  private
  def default_values
  	self.status ||= 1
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
	before_action :authenticate_user!

	def create
		@payment = current_user.payments.new(post_params)

		respond_to do |format|
			if @payment.save
				format.html {redirect_to cart_path}
				format.json {head :no_content}
			else
				redirect_to Post.find(post_params[:post_id]), error: "No pudimos procesar tu compra"
				format.json {head :no_content}
			end
		end
	end

	def cart
		@payments = current_user.payments.where(status:1)
	end

	def express
		price = current_user.total_to_pay
		response = EXPRESS_GATEWAY.setup_purchase(price*100,
				ip: request.remote_ip,
				return_url: "http://localhost:3000/transactions/checkout",
				cancel_return_url: "http://localhost:3000/cart",
				name: "Checkout de compras en BlogRails",
				amount: price*100
			)
		redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token, review: false)
	end

	def purchases
		@payments = current_user.payments.where(status:2)
	end

	private
	def post_params
		params.require(:payment).permit(:post_id)
	end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(payment) do |f| %>
	<% if payment.errors.any? %>
		<h2><%= pluralize(payment.errors.count, "error")%> evitaron que el pago se guardara </h2>
	<%end %>

	<div class="field">
		<%= f.hidden_field :post_id, value: post.id %>
	</div>
	<div class="actions">
		<%= content_tag :button, type: :submit, class: "btn btn-success" do %>
			<i class="fa fa-shopping-cart"></i> Comprar
		<% end %>
	</div>

<%end%>

app/views/payments/cart.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 center-block no-float">
			<h1> <i class="fa fa-shopping-cart"></i> Mi carrito </h1>

			<ul class="list-group">
				<% @payments.each do |payment| %>
					<li class="list-group-item">
						<div class="row">
							<div class="col-md-8 text-left">
								<%= payment.post.tittle%>
							</div>
							<div class="col-md-3 text-right">
								<%= "#{payment.post.price}USD" unless payment.post.price.nil? %>
							</div>
						</div>
					</li>
				<%end%>
				<li class="list-group-item">
					<div class="row">
						<div class="col-md-8">
							Total:
						</div>
						<div class="col-md-3 text-right">
							<%= current_user.total_to_pay %> USD
						</div>
					</div>
				</li>
			</ul>

		</div>
	</div>
</div>
<div class="text-center" data-no-turbolinks>
	<%= link_to(payments_express_path, class: "btn btn-success btn-lg") do %>
		<i class="fa fa-money"></i> Pagar
	<%end%>
</div>

app/views/payments/purchases.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 center-block no-float">
			<h1> <i class="fa fa-shopping-cart"></i> Mis compras </h1>

			<ul class="list-group">
				<% @payments.each do |payment| %>
					<li class="list-group-item">
						<%= link_to payment.post.tittle, payment.post %>
					</li>
				<%end%>
			</ul>
		</div>
	</div>
</div>