config/routes.rb
Rails.application.routes.draw do
  
  get "payments/express"

  resources :attachments
  resources :payments
  resources :posts

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks",
                                  registrations: "registrations"}

  resources :users

  post "users/follow"
  
  get 'welcome/index'

  get "/cart", to: "payments#cart"

  get "transactions/checkout"

  get "/purchases", to: "payments#purchases"

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/png" href="/assets/rails.png">
</head>
<body>
<p class="notice" style="<%= "display:none;" if notice.nil? %>"><%= notice %></p>
<p class="alert" style="<%= "display:none;" if alert.nil? %>"><%= alert %></p>
<header>
	<nav>
		<ul class="nav nav-tabs">
			<li>
				<%= link_to "Home", root_path %>
			</li>
			<li>
				<%= link_to "Posts", posts_path %>
			</li>
			<% if user_signed_in? %>
				<li>
					<%= link_to "Editar perfil", edit_user_registration_path(current_user) %>
				</li>
				<li>
					<%= link_to "Mi carrito", cart_path %>
				</li>
				<li>
					<%= link_to "Mi compras", purchases_path %>
				</li>
				<li>
					<%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
				</li>
			<% else %>
				<li>
					<%= link_to "Ingresar", new_user_session_path %>
				</li>
				<li>
					<%= link_to "Registrarse", new_user_registration_path %>
				</li>
			<%end%>
		</ul>
	</nav>
</header>
<section class="text-center">
	<%= yield %>
</section>


</body>
</html>